### ISSUE TITLE
При добавлении стека в LB  должно создаваться имя хоста

### ISSUE THREAD

**Issue by dmitryint** [Energy1190/flask-web-rancher#1]
<img width="384" alt="2017-11-10 21 38 14" src="https://user-images.githubusercontent.com/9825180/32673276-99a18a3a-c65f-11e7-886a-55dda4984f50.png">

**Comment by Energy1190** [comment]
Какое, где его взять? Из site-url? Или это должно быть что-то еще?

**Comment by dmitryint** [comment]
Да, hostname из siteurl

**Comment by Energy1190** [comment]
https://github.com/Energy1190/flask-web-rancher/pull/3

**Comment by Energy1190** [comment]
Закрываю.
