### ISSUE TITLE
При создании нового инстанса возникает ошибка.

### ISSUE THREAD

**Issue by dmitryint** [Energy1190/flask-web-rancher#10]
<img width="1168" alt="2017-11-11 17 09 09" src="https://user-images.githubusercontent.com/9825180/32690169-22f46160-c703-11e7-963b-2e90316bea50.png">

**Comment by dmitryint** [comment]
<img width="1044" alt="2017-11-11 17 12 39" src="https://user-images.githubusercontent.com/9825180/32690194-a0a9b718-c703-11e7-95ca-137895f6442f.png">

**Comment by Energy1190** [comment]
А сервис создался? Это бывает, когда ошибка в docker-compose.yaml, и сервис не может быть создан, соответственно и serviceId не будет.

**Comment by dmitryint** [comment]
да

**Comment by dmitryint** [comment]
http://appfurnish-rancher-webapp-1988606665.us-west-2.elb.amazonaws.com

**Comment by Energy1190** [comment]
RANCHER_SERVICE_NAME=nginx
